get "/" => "home#index"
get "/show" => "show#index"
get "/spring" => "spring#index"
get "/summer" => "summer#index"
get "/autumn" => "autumn#index"
get "/winter" => "winter#index"
get "/poem" => "poem#index"
get "/chess" => "chess#index"
